var data={
    "music":[
        {
            "song": "On Sight",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 1,
        },
        {
            "song": "Black Skinhead",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 2,
        },
        {
            "song": "I Am a God",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 3,
        },
        {
            "song": "New Slaves",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 4,
        },
        {
            "song": "Hold My Liquor",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 5,
        },
        {
            "song": "I'm in It",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 6,
        },
        {
            "song": "Blood on the Leaves",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 7,
        },
        {
            "song": "Guilt Trip",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 8,
        },
        {
            "song": "Send It Up",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 9,
        },
        {
            "song": "Bound 2",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 10,
        },
        {
            "song": "Dark Fantasy",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 1,
        },
        {
            "song": "Gorgeous",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 2,
        },
        {
            "song": "Power",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 3,
        },
        {
            "song": "All of the Lights (interlude)",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 4,
        },
        {
            "song": "All of the Lights",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 5,
        },
        {
            "song": "Monster",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 6,
        },
        {
            "song": "So Appalled",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 7,
        },
        {
            "song": "Devil in a New Dress",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 8,
        },
        {
            "song": "Runaway",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 9,
        },
        {
            "song": "Hell of a Life",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 10,
        },
        {
            "song": "Blame Game",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 11,
        },
        {
            "song": "Lost in the World",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 12,
        },
        {
            "song": "Who Will Survive in America",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 13,
        },
        {
            "song": "See Me Now",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 14,
        },
        {
            "song": "Good Morning",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 1,
        },
        {
            "song": "Champion",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 2,
        },
        {
            "song": "Stronger",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 3,
        },
        {
            "song": "I Wonder",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 4,
        },
        {
            "song": "Good Life",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 5,
        },
        {
            "song": "Can't Tell Me Nothing",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 6,
        },
        {
            "song": "Barry Bonds",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 7,
        },
        {
            "song": "Drunk & Hot Girls",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 8,
        },
        {
            "song": "Flashing Lights",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 9,
        },
        {
            "song": "Everything I Am",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 10,
        },
        {
            "song": "The Glory",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 11,
        },
        {
            "song": "Homecoming",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 12,
        },
        {
            "song": "Big Brother",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 13,
        },
        {
            "song": "Good Night",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 14,
        },
        {
            "song": "Bittersweet Poetry",
            "artist": "Kanye West",
            "album": "Graduation",
            "year": 2007,
            "tracknum": 15,
        },
        {
            "song": "Sun it Rises",
            "artist": "Fleet Foxes",
            "album": "Fleet Foxes",
            "year": 2008,
            "tracknum": 1,
        },
        {
            "song": "Black Treacle",
            "artist": "Arctic Monkeys",
            "album": "Suck It and See",
            "year": 2011,
            "tracknum": 2,
        },
        {
            "song": "Mixtape",
            "artist": "Brand New",
            "album": "Your Favorite Weapon",
            "year": 2001,
            "tracknum": 4,
        },
        {
            "song": "R U Mine?",
            "artist": "Arctic Monkeys",
            "album": "AM",
            "year": 2013,
            "tracknum": 2,
        },
        {
            "song": "One More Time",
            "artist": "Daft Punk",
            "album": "Discovery",
            "year": 2001,
            "tracknum": 1,
        },
        {
            "song": "For Sale? (Interlude)",
            "artist": "Kendrick Lamar",
            "album": "To Pimp a Butterfly",
            "year": 2015,
            "tracknum": 8,
        },
        {
            "song": "Brainstorm",
            "artist": "Arctic Monkeys",
            "album": "Favourite Worst Nightmare",
            "year": 2007,
            "tracknum": 1,
        }

    ],
    "covers": {
        "My Beautiful Dark Twisted Fantasy": "https://upload.wikimedia.org/wikipedia/en/f/f0/My_Beautiful_Dark_Twisted_Fantasy.jpg",
        "Graduation": "https://upload.wikimedia.org/wikipedia/en/7/70/Graduation_(album).jpg",
        "Yeezus": "https://griffinmiller47.files.wordpress.com/2014/08/tumblr_moelxko29e1qjo50co1_1371248265_cover.jpg",
        "Discovery": "https://upload.wikimedia.org/wikipedia/en/a/ae/Daft_Punk_-_Discovery.jpg",
        "Fleet Foxes": "img/album2.jpg",
        "Suck It and See": "img/album3.jpg",
        "Your Favorite Weapon": "img/album4.jpg",
        "AM": "img/album5.jpg",
        "To Pimp a Butterfly": "img/album6.jpeg",
        "Favourite Worst Nightmare": "img/album7.jpg",
    },
    "artists": {
        "Kanye West": "http://assets.rollingstone.com/assets/images/artists/kanye-west.jpg",
        "Daft Punk": "http://www.harderbloggerfaster.com/wp-content/uploads/2015/04/11052439_10153091601470673_6852645804799973936_n.jpg", 
        "Arctic Monkeys": "https://www.vipseats.com/images/arctic%20monkeys%20tickets.jpg", 
        "Brand New": "http://blog.tiqiq.com/wp-content/uploads/2015/02/BrandNewBandshot600.jpg",
        "Kendrick Lamar": "http://cdn4.pitchfork.com/tracks/14476/homepage_large.5ba6f1c6.jpg"
    }

}





