var data={
    "music":[
        {
            "song": "On Sight",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 1,
        },
        {
            "song": "Black Skinhead",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 2,
        },
        {
            "song": "I Am a God",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 3,
        },
        {
            "song": "New Slaves",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 4,
        },
        {
            "song": "Hold My Liquor",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 5,
        },
        {
            "song": "I'm in It",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 6,
        },
        {
            "song": "Blood on the Leaves",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 7,
        },
        {
            "song": "Guilt Trip",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 8,
        },
        {
            "song": "Send It Up",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 9,
        },
        {
            "song": "Bound 2",
            "artist": "Kanye West",
            "album": "Yeezus",
            "year": 2013,
            "tracknum": 10,
        },
        {
            "song": "Dark Fantasy",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 1,
        },
        {
            "song": "Gorgeous",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 2,
        },
        {
            "song": "Power",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 3,
        },
        {
            "song": "All of the Lights (interlude)",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 4,
        },
        {
            "song": "All of the Lights",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 5,
        },
        {
            "song": "Monster",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 6,
        },
        {
            "song": "So Appalled",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 7,
        },
        {
            "song": "Devil in a New Dress",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 8,
        },
        {
            "song": "Runaway",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 9,
        },
        {
            "song": "Hell of a Life",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 10,
        },
        {
            "song": "Blame Game",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 11,
        },
        {
            "song": "Lost in the World",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 12,
        },
        {
            "song": "Who Will Survive in America",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 13,
        },
        {
            "song": "See Me Now",
            "artist": "Kanye West",
            "album": "My Beautiful Dark Twisted Fantasy",
            "year": 2010,
            "tracknum": 14,
        },
]}

